#
# Api
#

api_solicitud_egreso:
    path: /api/solicitud-egreso
    controller: App\Controller\Procesos\IcSolicitudEgresoController::getApi

json_area:
    path: /json-area
    controller: App\Controller\Procesos\IcActivosFijosController::getArea

activos_fijos_index:
    path: /mis-herramientas-de-trajo
    controller: App\Controller\Procesos\IcActivosFijosController::index

activos-fijos:
    path: /activos
    controller: App\Controller\Procesos\IcActivosFijosController::getActivos

activos-fijose:
    path: /salida-activo-fijo/{activo}
    controller: App\Controller\Procesos\IcActivosFijosController::getSalida

activos_autorizacion:
    path: /salida-activo-fijo/{codigo}/verificacion/{correo}
    controller: App\Controller\Procesos\IcActivosFijosController::getAutorizacion

activos_solicitues:
    path: /solicitudes-salia
    controller: App\Controller\Procesos\IcActivosFijosController::getSolicitudes

activos_salida_fecha:
    path: /fecha-salida-activos-fijos
    controller: App\Controller\Procesos\IcActivosFijosController::getSalidaFecha
#
# Api Dashboard Info
#
pagos_proyectados_mes:
    path: /proyectados
    controller: App\Controller\Patrocinios\IcPagoProyectadoController::getPagosProyectados

count_patrocinadores:
    path: /count-patrocinadores
    controller: App\Controller\Patrocinios\IcPatrocinadorController::countPatrocinadores

depositos_pago:
    path: /depositos-pago
    controller: App\Controller\Patrocinios\IcPagoController::depositosPorPago