
#Rutas general del sistemas de procesos, no admin , no solicitudes
procesos_inicio:
  path: /
  controller: App\Controller\Procesos\IcHomeController::index

procesos_documentacion_egresos:
  path: /{id}/procedimiento/{nombre}
  controller: App\Controller\Procesos\IcHomeController::egresos
  requirements:
    id: '\d+'


procesos_tipo_control:
  path: /{idMacroproceso}/control/{nombre}
  controller: App\Controller\Procesos\IcHomeController::tipo
  requirements:
    idMacroproceso: '\d+'

procesos_menu_procedimiento:
  path: /{idProcedimiento}/menu-de-procedimientos
  controller: App\Controller\Procesos\IcHomeController::menuprocedimiento
  requirements:
    idProcedimiento: '\d+'


#
# procedimientos
#

public_procedimiento_procedimiento:
  path: /{id}/{nombre}/mostrar-procedimientos
  controller: App\Controller\Procesos\IcProcedimientosController::procedimiento 
  requirements:
    id: '\d+'

public_procedimiento_instruccion_trabajo:
  path: /{instruccion}/mostrar-instruccion-trabajo
  controller: App\Controller\Procesos\IcProcedimientosController::instruccion
  requirements:
    instruccion: '\d+'

#
# instruccion de trabajo
#

public_instruccion_mostrar:
  path: /{idInstructivo}/club-tijuana-mostrar-instruccion-de-trabajo
  controller: App\Controller\Procesos\IcInstruccionTrabajoController::show
  requirements:
    idInstructivo: '\d+'

#
# instructivo
#

public_instructivo_mostrar:
  path: /{iDescripcion}/club-tijuana-mostrar-instructivo-descripcion
  controller: App\Controller\Procesos\IcInstructivoController::show 
  requirements:
    iDescripcion: '\d+'