
#Rutas general del sistemas de procesos, no admin , no solicitudes
procesos_inicio:
  path: /
  defaults: { _controller: AppBundle:Default:index }

procesos_documentacion_egresos:
  path: /{id}/procedimiento/{nombre}
  defaults: { _controller: AppBundle:Default:egresos }
  requirements:
    id: '\d+'


procesos_tipo_control:
  path: /{idMacroproceso}/control/{nombre}
  defaults: { _controller: AppBundle:Default:tipo }
  requirements:
    idMacroproceso: '\d+'

procesos_menu_procedimiento:
  path: /{idProcedimiento}/menu-de-procedimientos.html
  defaults: { _controller: AppBundle:Default:menuprocedimiento}
  requirements:
    idProcedimiento: '\d+'

public_procedimiento_procedimiento:
  path: /{id}/{nombre}/mostrar-procedimientos.html
  defaults: { _controller: AppBundle:IcProcedimientos:procedimiento }
  requirements:
    id: '\d+'

public_procedimiento_instruccion_trabajo:
  path: /{instruccion}/mostrar-instruccion-trabajo.html
  defaults: { _controller: AppBundle:IcProcedimientos:instruccion }
  requirements:
    instruccion: '\d+'

#
# Solicitud de Egreso
#

solicitud_egresos_usuario:
  path: /solicitud-de-egreso-por-usuario
  defaults: { _controller: AppBundle:IcSolicitud:index }


#
# Solicitud de Personal
#

procesos_personal:
  path: /recursos-humanos
  defaults: { _controller: ProcesosBundle:IcSolicitudPersonal:index }

procesos_personal_lista_gerencia:
  path: /lista-de-personal-por-gerencia/{idGerencia}
  defaults: { _controller: ProcesosBundle:IcSolicitudPersonal:listaPorGerencia }
  requirements:
    idGerencia: '\d+'

procesos_alta_personal:
  path: /nueva-solicitud-personal/{idArea}
  defaults: { _controller: ProcesosBundle:IcSolicitudPersonal:new }
  requirements:
    idArea: '\d+'

procesos_baja_personal:
  path: /baja-solicitud-personal/{idArea}
  defaults: { _controller: ProcesosBundle:IcSolicitudPersonal:baja }
  requirements:
    idArea: '\d+'