#
# Rutas solicitud de Egresos
#

reportes_gestion_marca:
    path: /reportes-gestion-de-marca
    controller: AppBundle:IcReportesGestionMarca:direccion

reportes_general:
    path: /resumen-general-gestion-marca
    controller: AppBundle:IcReportesGestionMarca:general

reportes_gestion_recursos:
    path: /reportes-gestion-recursos
    controller: AppBundle:IcSolicitudEgreso:index

reportes_gestion_deportiva:
    path: /reportes-gestion-deportiva
    controller: AppBundle:IcSolicitudEgreso:index